insert into Brand (Name, Rating, Type) values ('Anthropologie', 8, 'Unique, full-lifestyle shopping');
insert into Brand (Name, Rating, Type) values ('Alo Yoga', 9, 'Technologically advanced yoga clothing');
insert into Brand (Name, Rating, Type) values ('Ami Paris', 10, 'Contemporary and authentic fashion');
insert into Brand (Name, Rating, Type) values ('Aritzia', 10, 'Everyday luxury');
insert into Brand (Name, Rating, Type) values ('Banana Republic', 9, 'Chic and modern casualwear');
insert into Brand (Name, Rating, Type) values ('Brandy Melville', 7, 'Trendy comfortable clothing');
insert into Brand (Name, Rating, Type) values ('Burberry', 10, 'British high end fashion house');
insert into Brand (Name, Rating, Type) values ('Calvin Klein', 8, 'Simple, comfortable, but stylish clothes');
insert into Brand (Name, Rating, Type) values ('Carhartt', 8, 'Classic clothing with high durability');
insert into Brand (Name, Rating, Type) values ('Champion', 7, 'Classic sportswear');
insert into Brand (Name, Rating, Type) values ('Coach', 8, 'Authentic fashion house founded in New York');
insert into Brand (Name, Rating, Type) values ('Comme des Garcons', 9, 'Unique, iconic fashion house founded in Japan');
insert into Brand (Name, Rating, Type) values ('COS', 8, 'Ready-to-wear with high focus on craftmanship and sustainability');
insert into Brand (Name, Rating, Type) values ('Diesel', 9, 'Global leader in denim fashion');
insert into Brand (Name, Rating, Type) values ('Everlane', 7, 'Modern basics');
insert into Brand (Name, Rating, Type) values ('Forever 21', 5, 'Fashion basics');
insert into Brand (Name, Rating, Type) values ('H&M', 5, 'Customer-focused essential apparel');
insert into Brand (Name, Rating, Type) values ('Kate Spade', 7, 'Independent and playful fashion brand from New York');
insert into Brand (Name, Rating, Type) values ('Levi', 8, 'Authentic jeanswear');
insert into Brand (Name, Rating, Type) values ('Madewell', 7, 'Staple fashion for everyone');
insert into Brand (Name, Rating, Type) values ('Maison Kitsune', 10, 'French-Japanese lifestyle brand');
insert into Brand (Name, Rating, Type) values ('Massimo Dutti', 8, 'Design with exclusive materials and fabrics');
insert into Brand (Name, Rating, Type) values ('Max Mara', 10, 'High end classic ready-to-wear');
insert into Brand (Name, Rating, Type) values ('Nike', 8, 'Worlds largest athletic apparel');
insert into Brand (Name, Rating, Type) values ('Oak + Fort', 7, 'Modern, trendy lifestyle brand');
insert into Brand (Name, Rating, Type) values ('Old Navy', 6, 'Must-have fashion essentials');
insert into Brand (Name, Rating, Type) values ('PacSun', 6, 'Youth-inspired apparel');
insert into Brand (Name, Rating, Type) values ('Patagonia', 10, 'Environmentally sustainable outdoor clothing');
insert into Brand (Name, Rating, Type) values ('Polo Ralph Lauren', 10, 'Classic luxury lifestyle');
insert into Brand (Name, Rating, Type) values ('Prada', 10, 'Italian unique luxury fashion house');
insert into Brand (Name, Rating, Type) values ('Rag&Bone', 9, 'Classic yet modern ready-to-wear');
insert into Brand (Name, Rating, Type) values ('Reformation', 8, 'Sustainable, trendy clothing');
insert into Brand (Name, Rating, Type) values ('Saint Laurent', 10, 'Paris leading fashion house');
insert into Brand (Name, Rating, Type) values ('Stussy', 9, 'Unique skate/streetwear brand');
insert into Brand (Name, Rating, Type) values ('The North Face', 9, 'Advanced outdoor products for everyone');
insert into Brand (Name, Rating, Type) values ('Theory', 7, 'Contemporary fashion label');
insert into Brand (Name, Rating, Type) values ('Tommy Hilfiger', 8, 'Premium style and quality');
insert into Brand (Name, Rating, Type) values ('Uniqlo', 8, 'Minimalistic global clothing brand');
insert into Brand (Name, Rating, Type) values ('Urban Outfitters', 7, 'Experiential fashion retail with a wide variety of styles');
insert into Brand (Name, Rating, Type) values ('Zara', 6, 'Simple, chic clothing');
