insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('S', 'Shoulder bag', '', 139.40, '15', '6', '22', 'Coach', '20');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XS', 'Turtleneck Sweater', '', 96.14, '6', '20', '16', 'Aritzia', '18');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('3XL', 'Simple T-Shirt', 'Lorem Ipsum', 48.00, '19', '11', '14', 'Anthropologie', '7');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('2XL', 'Party Dress', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 55.62, '12', '13', '36', 'Everlane', '26');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Denim Tote', '', 62.93, '13', '19', '6', 'H&M', '1');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Oversized Top', 'Ut at dolor quis odio consequat varius.', 59.00, '1', '12', '37', 'Uniqlo', '14');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('M', 'Silk Long Skirt', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu.', 18.89, '10', '16', '9', 'Brandy Melville', '3');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Spring Dress', 'Praesent lectus.', 3.7, '20', '4', '25', 'Urban Outfitters', '5');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XS', 'Faux Fur Coat', '', 60.82, '8', '17', '5', 'Urban Outfitters', '12');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Winter Cardigan', '', 93.60, '9', '8', '31', 'Ami Paris', '25');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Winter Sweater', '', 12.00, '3', '7', '18', 'Forever 21', '27');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('M', 'Minimalistic Shirt', 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 10.47, '5', '9', '12', 'COS', '8');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('M', 'Velvet Oversized Jacket', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 94.83, '4', '14', '2', 'Carhartt', '4');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Baggy Jeans', 'Mauris sit amet eros.', 125.50, '14', '2', '8', 'Diesel', '30');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Button-up Shirt', 'Nulla mollis molestie lorem.', 42.99, '16', '15', '20', 'Massimo Dutti', '28');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Racer Jacket', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 82.00, '2', '5', '38', 'Diesel', '22');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('2XL', 'Cropped Outerwear', '', 3.15, '11', '3', '35', 'Old Navy', '21');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('S', 'Logo Tee', '', 97.46, '17', '1', '19', 'Stussy', '16');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Comfy Pants', 'Vivamus tortor.', 29.75, '18', '10', '4', 'Zara', '15');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XS', 'Rain Jacket', 'Praesent lectus.', 77.54, '7', '18', '32', 'Uniqlo', '29');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('S', 'High-collar Dress', '', 10.84, '1', '4', '23', 'Oak + Fort', '13');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XS', 'Ripped Denim Jacket', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 32.85, '17', '3', '7', 'PacSun', '11');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('S', 'Mini Denim Bag', '', 3.54, '2', '19', '34', 'Zara', '9');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Basic Tee', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 68.42, '11', '1', '28', 'Max Mara', '19');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('M', 'Medium Denim Tote', '', 45.19, '19', '10', '26', 'Madewell', '10');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Logo T-shirt', 'Morbi a ipsum. Integer a nibh.', 62.99, '12', '2', '17', 'Comme des Garcons', '17');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Wide-leg Pants', 'Suspendisse potenti. In eleifend quam a odio.', 111.35, '3', '5', '3', 'Aritzia', '24');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Silk Fitted Skirt', 'Suspendisse potenti. In eleifend quam a odio.', 83.75, '15', '16', '27', 'Reformation', '2');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XS', 'Cute Sweater', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. .', 93.25, '7', '7', '39', 'Aritzia', '6');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Thin knitted top', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue.', 57.99, '6', '20', '40', 'Uniqlo', '23');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('2XL', 'Long Velvet Dress', 'Fusce posuere felis sed lacus.', 14.25, '16', '13', '15', 'H&M', '20');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('M', 'Cropped Fur Coat', 'Nulla ac enim.', 71.57, '18', '17', '21', 'Reformation', '22');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('M', 'Minimalistic Cardigan', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 18.91, '20', '8', '11', 'PacSun', '7');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('L', 'Simple Jacket', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 53.76, '10', '18', '1', 'Patagonia', '14');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Leather Tote', '', 48.79, '4', '6', '24', 'Urban Outfitters', '23');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('S', 'Oversized Silk Shirt', 'Etiam justo.', 8.34, '13', '15', '30', 'Forever 21', '16');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('3XL', 'Linen Button-up Shirt', '', 83.58, '5', '9', '10', 'Banana Republic', '27');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XL', 'Vintage Sweater', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 70.31, '14', '11', '29', 'Champion', '13');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('3XL', 'Oversized Jacket', '', 92.35, '8', '14', '33', 'Patagonia', '28');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('S', 'Simple Oversized T-Shirt', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.', 58.84, '9', '12', '13', 'Nike', '1');
insert into Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) values ('XS', 'Slim Top', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 38.65, '9', '15', '32', 'Brandy Melville', '15');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('M', 'Straight Jeans', 'Donec quis orci eget orci vehicula condimentum.', 40.58, '15', '2', '28', 'Levi', '10');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XL', 'Oversized Hoodie', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 84.17, '6', '11', '27', 'Champion', '24');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('S', 'Casual Short Sleeve Top', '', 78.49, '14', '1', '19', 'The North Face', '6');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('3XL', 'Fluffy Jacket', 'Integer ac leo.', 48.85, '13', '8', '23', 'Patagonia', '11');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('L', 'Denim Large Tote', '', 15.10, '2', '19', '35', 'H&M', '30');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('L', 'Simple Denim Jacket', 'Aliquam erat volutpat.', 33.29, '8', '3', '7', 'Everlane', '29');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XS', 'Thin Wool Sweater', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.', 111.75, '10', '7', '30', 'Polo Ralph Lauren', '25');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('2XL', 'Long Leather Coat', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 136.15, '4', '5', '15', 'Banana Republic', '2');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XL', 'Nylon Jacket', 'Aenean sit amet justo. Morbi ut odio.', 65.67, '3', '18', '21', 'The North Face', '18');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('S', 'Summer Dress', 'In blandit ultrices enim.', 48.65, '17', '4', '10', 'Zara', '26');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('2XL', 'Wide-leg Linen Pants', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 42.08, '20', '10', '12', 'Polo Ralph Lauren', '8');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('2XL', 'Simple Top', '', 76.45, '7', '9', '38', 'Stussy', '17');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XS', 'Slim Skirt', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 44.99, '5', '16', '34', 'Madewell', '3');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XL', 'Knit Sweater', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero.', 30.07, '16', '20', '33', 'Uniqlo', '19');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XS', 'Long Fur Coat', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 51.23, '12', '17', '26', 'Oak + Fort', '9');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('M', 'Half-zip Sweater', '', 52.05, '11', '11', '9', 'Patagonia', '5');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('S', 'Mini Leather Cross-body Bag', 'Phasellus in felis.', 140.99, '18', '6', '6', 'Kate Spade', '21');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('3XL', 'Oversized Hoodie', 'Etiam justo. Etiam pretium iaculis justo.', 85.75, '1', '11', '8', 'Nike', '12');
INSERT INTO Clothing_Item (Size, Name, Description, Price, DiscountID, CategoryID, CartID, BrandName, StyleID) VALUES ('XS', 'Mini Dress', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 60.00, '19', '13', '24', 'Aritzia', '4');

/* Insert Item_Outfit */
insert into Item_Outfit (ItemID, OutfitID) values ('59', '3');
insert into Item_Outfit (ItemID, OutfitID) values ('29', '29');
insert into Item_Outfit (ItemID, OutfitID) values ('11', '1');
insert into Item_Outfit (ItemID, OutfitID) values ('51', '25');
insert into Item_Outfit (ItemID, OutfitID) values ('17', '9');
insert into Item_Outfit (ItemID, OutfitID) values ('45', '28');
insert into Item_Outfit (ItemID, OutfitID) values ('15', '30');
insert into Item_Outfit (ItemID, OutfitID) values ('38', '24');
insert into Item_Outfit (ItemID, OutfitID) values ('19', '47');
insert into Item_Outfit (ItemID, OutfitID) values ('7', '40');
insert into Item_Outfit (ItemID, OutfitID) values ('43', '17');
insert into Item_Outfit (ItemID, OutfitID) values ('3', '45');
insert into Item_Outfit (ItemID, OutfitID) values ('26', '7');
insert into Item_Outfit (ItemID, OutfitID) values ('57', '4');
insert into Item_Outfit (ItemID, OutfitID) values ('20', '23');
insert into Item_Outfit (ItemID, OutfitID) values ('49', '16');
insert into Item_Outfit (ItemID, OutfitID) values ('9', '46');
insert into Item_Outfit (ItemID, OutfitID) values ('41', '13');
insert into Item_Outfit (ItemID, OutfitID) values ('40', '22');
insert into Item_Outfit (ItemID, OutfitID) values ('36', '33');
insert into Item_Outfit (ItemID, OutfitID) values ('4', '14');
insert into Item_Outfit (ItemID, OutfitID) values ('37', '43');
insert into Item_Outfit (ItemID, OutfitID) values ('32', '18');
insert into Item_Outfit (ItemID, OutfitID) values ('25', '36');
insert into Item_Outfit (ItemID, OutfitID) values ('28', '50');
insert into Item_Outfit (ItemID, OutfitID) values ('1', '10');
insert into Item_Outfit (ItemID, OutfitID) values ('30', '49');
insert into Item_Outfit (ItemID, OutfitID) values ('39', '6');
insert into Item_Outfit (ItemID, OutfitID) values ('2', '41');
insert into Item_Outfit (ItemID, OutfitID) values ('16', '31');
insert into Item_Outfit (ItemID, OutfitID) values ('23', '8');
insert into Item_Outfit (ItemID, OutfitID) values ('22', '34');
insert into Item_Outfit (ItemID, OutfitID) values ('35', '35');
insert into Item_Outfit (ItemID, OutfitID) values ('5', '2');
insert into Item_Outfit (ItemID, OutfitID) values ('54', '37');
insert into Item_Outfit (ItemID, OutfitID) values ('18', '19');
insert into Item_Outfit (ItemID, OutfitID) values ('34', '26');
insert into Item_Outfit (ItemID, OutfitID) values ('60', '32');
insert into Item_Outfit (ItemID, OutfitID) values ('33', '42');
insert into Item_Outfit (ItemID, OutfitID) values ('14', '44');
insert into Item_Outfit (ItemID, OutfitID) values ('42', '20');
insert into Item_Outfit (ItemID, OutfitID) values ('6', '27');
insert into Item_Outfit (ItemID, OutfitID) values ('53', '15');
insert into Item_Outfit (ItemID, OutfitID) values ('8', '48');
insert into Item_Outfit (ItemID, OutfitID) values ('56', '38');
insert into Item_Outfit (ItemID, OutfitID) values ('46', '21');
insert into Item_Outfit (ItemID, OutfitID) values ('27', '12');
insert into Item_Outfit (ItemID, OutfitID) values ('31', '5');
insert into Item_Outfit (ItemID, OutfitID) values ('52', '11');
insert into Item_Outfit (ItemID, OutfitID) values ('24', '39');
insert into Item_Outfit (ItemID, OutfitID) values ('12', '16');
insert into Item_Outfit (ItemID, OutfitID) values ('13', '19');
insert into Item_Outfit (ItemID, OutfitID) values ('48', '44');
insert into Item_Outfit (ItemID, OutfitID) values ('21', '14');
insert into Item_Outfit (ItemID, OutfitID) values ('50', '8');
insert into Item_Outfit (ItemID, OutfitID) values ('44', '34');
insert into Item_Outfit (ItemID, OutfitID) values ('10', '10');
insert into Item_Outfit (ItemID, OutfitID) values ('47', '37');
insert into Item_Outfit (ItemID, OutfitID) values ('58', '46');
insert into Item_Outfit (ItemID, OutfitID) values ('55', '4');
insert into Item_Outfit (ItemID, OutfitID) values ('59', '7');
insert into Item_Outfit (ItemID, OutfitID) values ('9', '38');
insert into Item_Outfit (ItemID, OutfitID) values ('28', '39');
insert into Item_Outfit (ItemID, OutfitID) values ('19', '11');
insert into Item_Outfit (ItemID, OutfitID) values ('60', '29');
insert into Item_Outfit (ItemID, OutfitID) values ('4', '15');
insert into Item_Outfit (ItemID, OutfitID) values ('30', '48');
insert into Item_Outfit (ItemID, OutfitID) values ('32', '30');
insert into Item_Outfit (ItemID, OutfitID) values ('10', '26');
insert into Item_Outfit (ItemID, OutfitID) values ('58', '23');
insert into Item_Outfit (ItemID, OutfitID) values ('5', '12');
insert into Item_Outfit (ItemID, OutfitID) values ('29', '3');
insert into Item_Outfit (ItemID, OutfitID) values ('47', '42');
insert into Item_Outfit (ItemID, OutfitID) values ('1', '21');
insert into Item_Outfit (ItemID, OutfitID) values ('40', '5');
insert into Item_Outfit (ItemID, OutfitID) values ('44', '43');
insert into Item_Outfit (ItemID, OutfitID) values ('41', '28');
insert into Item_Outfit (ItemID, OutfitID) values ('11', '22');
insert into Item_Outfit (ItemID, OutfitID) values ('34', '35');
insert into Item_Outfit (ItemID, OutfitID) values ('57', '6');
insert into Item_Outfit (ItemID, OutfitID) values ('24', '13');
insert into Item_Outfit (ItemID, OutfitID) values ('50', '27');
insert into Item_Outfit (ItemID, OutfitID) values ('2', '33');
insert into Item_Outfit (ItemID, OutfitID) values ('26', '25');
insert into Item_Outfit (ItemID, OutfitID) values ('48', '20');
insert into Item_Outfit (ItemID, OutfitID) values ('53', '17');
insert into Item_Outfit (ItemID, OutfitID) values ('35', '31');
insert into Item_Outfit (ItemID, OutfitID) values ('37', '47');
insert into Item_Outfit (ItemID, OutfitID) values ('8', '36');
insert into Item_Outfit (ItemID, OutfitID) values ('52', '40');
insert into Item_Outfit (ItemID, OutfitID) values ('15', '50');
insert into Item_Outfit (ItemID, OutfitID) values ('33', '9');
insert into Item_Outfit (ItemID, OutfitID) values ('13', '18');
insert into Item_Outfit (ItemID, OutfitID) values ('12', '49');
insert into Item_Outfit (ItemID, OutfitID) values ('22', '41');
insert into Item_Outfit (ItemID, OutfitID) values ('21', '1');
insert into Item_Outfit (ItemID, OutfitID) values ('49', '45');
insert into Item_Outfit (ItemID, OutfitID) values ('25', '24');
insert into Item_Outfit (ItemID, OutfitID) values ('16', '2');
insert into Item_Outfit (ItemID, OutfitID) values ('17', '32');
insert into Item_Outfit (ItemID, OutfitID) values ('56', '22');
insert into Item_Outfit (ItemID, OutfitID) values ('27', '5');
insert into Item_Outfit (ItemID, OutfitID) values ('36', '38');
insert into Item_Outfit (ItemID, OutfitID) values ('42', '6');
insert into Item_Outfit (ItemID, OutfitID) values ('31', '44');
insert into Item_Outfit (ItemID, OutfitID) values ('7', '13');
insert into Item_Outfit (ItemID, OutfitID) values ('54', '36');
insert into Item_Outfit (ItemID, OutfitID) values ('20', '32');
insert into Item_Outfit (ItemID, OutfitID) values ('43', '12');
insert into Item_Outfit (ItemID, OutfitID) values ('23', '48');
insert into Item_Outfit (ItemID, OutfitID) values ('3', '46');
insert into Item_Outfit (ItemID, OutfitID) values ('45', '21');
insert into Item_Outfit (ItemID, OutfitID) values ('38', '20');
insert into Item_Outfit (ItemID, OutfitID) values ('39', '4');
insert into Item_Outfit (ItemID, OutfitID) values ('55', '28');
insert into Item_Outfit (ItemID, OutfitID) values ('18', '10');
insert into Item_Outfit (ItemID, OutfitID) values ('14', '29');
insert into Item_Outfit (ItemID, OutfitID) values ('46', '16');
insert into Item_Outfit (ItemID, OutfitID) values ('6', '40');
insert into Item_Outfit (ItemID, OutfitID) values ('51', '7');
insert into Item_Outfit (ItemID, OutfitID) values ('9', '8');
insert into Item_Outfit (ItemID, OutfitID) values ('29', '33');
insert into Item_Outfit (ItemID, OutfitID) values ('42', '50');
insert into Item_Outfit (ItemID, OutfitID) values ('2', '2');
insert into Item_Outfit (ItemID, OutfitID) values ('52', '39');
insert into Item_Outfit (ItemID, OutfitID) values ('18', '27');
insert into Item_Outfit (ItemID, OutfitID) values ('47', '7');
insert into Item_Outfit (ItemID, OutfitID) values ('21', '17');
insert into Item_Outfit (ItemID, OutfitID) values ('55', '1');
insert into Item_Outfit (ItemID, OutfitID) values ('35', '9');
insert into Item_Outfit (ItemID, OutfitID) values ('36', '19');
insert into Item_Outfit (ItemID, OutfitID) values ('39', '45');
insert into Item_Outfit (ItemID, OutfitID) values ('6', '18');
insert into Item_Outfit (ItemID, OutfitID) values ('24', '41');
insert into Item_Outfit (ItemID, OutfitID) values ('46', '35');
insert into Item_Outfit (ItemID, OutfitID) values ('31', '31');
insert into Item_Outfit (ItemID, OutfitID) values ('1', '34');
insert into Item_Outfit (ItemID, OutfitID) values ('3', '42');
insert into Item_Outfit (ItemID, OutfitID) values ('33', '30');
insert into Item_Outfit (ItemID, OutfitID) values ('25', '23');
insert into Item_Outfit (ItemID, OutfitID) values ('51', '26');
insert into Item_Outfit (ItemID, OutfitID) values ('49', '14');
insert into Item_Outfit (ItemID, OutfitID) values ('13', '43');
insert into Item_Outfit (ItemID, OutfitID) values ('26', '24');
insert into Item_Outfit (ItemID, OutfitID) values ('7', '25');
insert into Item_Outfit (ItemID, OutfitID) values ('43', '15');
insert into Item_Outfit (ItemID, OutfitID) values ('16', '3');
insert into Item_Outfit (ItemID, OutfitID) values ('28', '49');
insert into Item_Outfit (ItemID, OutfitID) values ('4', '11');
insert into Item_Outfit (ItemID, OutfitID) values ('48', '47');
insert into Item_Outfit (ItemID, OutfitID) values ('11', '13');
insert into Item_Outfit (ItemID, OutfitID) values ('56', '17');
insert into Item_Outfit (ItemID, OutfitID) values ('38', '48');
insert into Item_Outfit (ItemID, OutfitID) values ('54', '30');
insert into Item_Outfit (ItemID, OutfitID) values ('41', '42');
insert into Item_Outfit (ItemID, OutfitID) values ('60', '22');
insert into Item_Outfit (ItemID, OutfitID) values ('27', '33');
insert into Item_Outfit (ItemID, OutfitID) values ('20', '12');
insert into Item_Outfit (ItemID, OutfitID) values ('58', '18');
insert into Item_Outfit (ItemID, OutfitID) values ('19', '43');
insert into Item_Outfit (ItemID, OutfitID) values ('5', '29');
insert into Item_Outfit (ItemID, OutfitID) values ('17', '14');
insert into Item_Outfit (ItemID, OutfitID) values ('30', '30');
insert into Item_Outfit (ItemID, OutfitID) values ('45', '39');
insert into Item_Outfit (ItemID, OutfitID) values ('32', '34');
insert into Item_Outfit (ItemID, OutfitID) values ('37', '11');
insert into Item_Outfit (ItemID, OutfitID) values ('8', '32');
insert into Item_Outfit (ItemID, OutfitID) values ('10', '40');
insert into Item_Outfit (ItemID, OutfitID) values ('14', '19');
insert into Item_Outfit (ItemID, OutfitID) values ('53', '7');
insert into Item_Outfit (ItemID, OutfitID) values ('57', '25');
insert into Item_Outfit (ItemID, OutfitID) values ('15', '20');
insert into Item_Outfit (ItemID, OutfitID) values ('50', '46');
insert into Item_Outfit (ItemID, OutfitID) values ('23', '16');
insert into Item_Outfit (ItemID, OutfitID) values ('44', '3');
insert into Item_Outfit (ItemID, OutfitID) values ('34', '37');
insert into Item_Outfit (ItemID, OutfitID) values ('22', '15');
insert into Item_Outfit (ItemID, OutfitID) values ('59', '10');
insert into Item_Outfit (ItemID, OutfitID) values ('12', '39');
insert into Item_Outfit (ItemID, OutfitID) values ('40', '35');
insert into Item_Outfit (ItemID, OutfitID) values ('56', '5');
insert into Item_Outfit (ItemID, OutfitID) values ('3', '28');
insert into Item_Outfit (ItemID, OutfitID) values ('44', '23');
insert into Item_Outfit (ItemID, OutfitID) values ('15', '2');
insert into Item_Outfit (ItemID, OutfitID) values ('57', '31');
insert into Item_Outfit (ItemID, OutfitID) values ('38', '6');
insert into Item_Outfit (ItemID, OutfitID) values ('15', '9');
insert into Item_Outfit (ItemID, OutfitID) values ('52', '38');
insert into Item_Outfit (ItemID, OutfitID) values ('31', '4');
insert into Item_Outfit (ItemID, OutfitID) values ('47', '1');
insert into Item_Outfit (ItemID, OutfitID) values ('2', '50');
insert into Item_Outfit (ItemID, OutfitID) values ('1', '44');
insert into Item_Outfit (ItemID, OutfitID) values ('11', '27');
insert into Item_Outfit (ItemID, OutfitID) values ('49', '24');
insert into Item_Outfit (ItemID, OutfitID) values ('18', '45');
insert into Item_Outfit (ItemID, OutfitID) values ('43', '41');
insert into Item_Outfit (ItemID, OutfitID) values ('14', '8');
insert into Item_Outfit (ItemID, OutfitID) values ('41', '21');
insert into Item_Outfit (ItemID, OutfitID) values ('40', '26');
insert into Item_Outfit (ItemID, OutfitID) values ('55', '47');
