insert into Discount (Name, Amount, Description) values ('10% Off', 10, '10% off all items');
insert into Discount (Name, Amount, Description) values ('Flash Sale', 50, 'Take 50% off all items');
insert into Discount (Name, Amount, Description) values ('Black Friday Deals', 70, 'Up to 70% off all items');
insert into Discount (Name, Amount, Description) values ('$8 Off Tops', 8, '$8 off all tops');
insert into Discount (Name, Amount, Description) values ('$10 Off Outerwear', 10, '$10 off all outerwear');
insert into Discount (Name, Amount, Description) values ('Clearance Discounts', 80, 'Up to 80% off clearance items');
insert into Discount (Name, Amount, Description) values ('Cyber Monday Sale', 50, '50% off all items');
insert into Discount (Name, Amount, Description) values ('$7 Off Bags', 7, '$7 off all bags');
insert into Discount (Name, Amount, Description) values ('24-Hour Sale', 40, '40% off all items in 24-hour');
insert into Discount (Name, Amount, Description) values ('Winter Blowout', 25, '25% off outerwear, and knit and wool tops');
insert into Discount (Name, Amount, Description) values ('Spring Sale', 20, '20% off all tops');
insert into Discount (Name, Amount, Description) values ('25% Off Dresses', 25, '25% off all dresses');
insert into Discount (Name, Amount, Description) values ('$5 Off', 5, '$5 off all orders');
insert into Discount (Name, Amount, Description) values ('20% Off', 20, '20% off all items');
insert into Discount (Name, Amount, Description) values ('Final Sale', 70, '70% off last chance pieces');
insert into Discount (Name, Amount, Description) values ('Limited Offer', 10, '$10 off for orders above $50');
insert into Discount (Name, Amount, Description) values ('Summer Sale', 15, '15% off cotton tops and bottoms');
insert into Discount (Name, Amount, Description) values ('Back To School Discounts', 10, '10% off all tops, bottoms, and dresses');
insert into Discount (Name, Amount, Description) values ('Early Sale', 10, '10% off all tops');
insert into Discount (Name, Amount, Description) values ('End of Year Sale', 20, '20% off all items');
