insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Flash Sale Alert!', 'Grab your favorites before they are gone', '2023-06-06 03:30:44');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('New Arrivals', 'Take a look at our new fashion finds!', '2023-09-15 17:52:58');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Half Price Alert', 'All items are 50% off!!!', '2023-03-09 04:43:41');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Your Wishlist items are on sale!', 'Check out your wishlist now!', '2023-02-21 05:01:13');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('$8 Off All Tops', 'Check out your favorite tops!', '2023-06-02 23:58:48');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Alert! 20% Off', 'Your favorite items are now 20% off', '2023-05-01 15:11:31');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Limited Offer Today', '$10 off all orders above $50', '2023-01-11 11:15:01');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('BLACK FRIDAY DEALS', 'Biggest sale of the year is here!', '2023-11-24 11:24:10');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Winter Blowout', '25% off outerwear, wool, and knit tops', '2023-11-03 03:42:44');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Spring Sale Is Here!', 'Your favorite tops are 25% off now', '2023-08-15 10:44:37');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Weekend Flash Sale', 'Check out amazing outfits at 50% off', '2023-04-18 04:47:19');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Newly Curated Outfits!', 'You will definitely love these outfits', '2023-01-05 13:25:24');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('CYBER MONDAY', 'Miss out Black Friday deals? - 50% off everything today! ', '2023-11-27 02:56:19');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Clearance Discounts Only Today', 'Selected items at 80% discount', '2023-05-16 15:44:54');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Amazing Deals', 'Selected items up to 70% off', '2022-12-31 22:04:15');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Hurry! Limited Deals', '$7 off all trendy bags', '2023-08-11 22:22:56');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('New items from your favorite brands', 'Your favorite brands just dropped new styles', '2023-05-01 01:16:32');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Add your wishlist to the cart now!', '$5 off everything only today', '2023-07-19 19:38:30');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Your Order is Ready!', 'Your order is ready to be shipped to you, we will keep you updated!', '2023-10-03 00:23:28');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Personalized Picks', 'Check out new outfits we have curated for YOU!', '2023-05-03 15:04:31');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Your Order is on the way', 'Your Order will arrive soon! Look out for our notifications', '2023-10-24 15:06:43');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Last piece - check out now!', 'Your favorite items are running out', '2023-01-13 15:34:59');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Your Order has arrived!', 'Your order has been delivered - Let us know your feedback!', '2023-02-04 17:16:23');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('We hope you enjoy your order!', 'Let us know your experience', '2023-03-13 11:52:51');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Trend Alert!', 'Trendy collection has just arrived', '2023-07-13 04:25:01');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Upgrade Your Wardrobe', 'Personalized outfits to enhance your everyday styles!', '2023-01-24 20:21:32');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Sneak Peek at the New Collection', 'Check out the new collection from our beloved brands', '2022-12-21 02:26:32');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Thank you for shopping with us!', 'We hope you have an amazing experience. We will keep you updated on your order!', '2023-01-26 08:41:45');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('Ready for Summer Discount?', 'Add new items to your summer collection', '2023-05-22 23:21:32');
insert into Notifications (SubjectLine, Messages, TimeStamp) values ('24H Sale!', '40% off all styles only today', '2023-10-25 23:47:41');
