INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Vintage', 'Classic Fit', 128.41, '$$', 'Vintage Winter Outfit', '21');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Gorpcore', 'Slim Fit', 616.35, '$$$', 'WaterProof Fit', '16');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Classic Fit', 92.55, '$', 'Back to School Essential', '36');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Classic Fit', 32.32, '$', 'Office Essential', '11');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Vintage', 'Slim Fit', 134.72, '$$', 'Vintage Party', '6');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Cottagecore', 'Classic Fit', 60.54, '$', 'Nature', '38');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Academia', 'Classic Fit', 88.70, '$', 'Dark Academia Winter Outfit', '8');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Academia', 'Classic Fit', 75.19, '$', 'Classic', '9');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Streetwear', 'Oversized Fit', 147.66, '$$', 'Comfy Cool Fit', '32');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Streetwear', 'Oversized Fit', 97.87, '$', 'Streetwear Fit', '25');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Streetwear', 'Slim Fit', 323.79, '$$$', 'Cool Outfit', '24');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Quiet Luxury', 'Slim Fit', 320.51, '$$$', 'Minimalistic Outift', '29');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Slim Fit', 858.6, '$$$', 'Clean Girl Oufit', '26');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Cottagecore', 'Slim Fit', 131.71, '$$', 'Cottage', '27');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Y2K', 'Slim Fit', 171.61, '$$', 'Colorful Y2K Fit', '14');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Gorpcore', 'Oversized Fit', 413.67, '$$$', 'AllBlack Outfit', '10');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Streetwear', 'Classic Fit', 86.61, '$', 'Streetwear Full Outfit', '34');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Quiet Luxury', 'Classic Fit', 74.47, '$', 'Elegance', '40');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Quiet Luxury', 'Classic Fit', 98.28, '$', 'Everyday Elegance', '35');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Classic Fit', 56.73, '$', 'Everyday Casual', '39');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Y2K', 'Slim Fit', 258.93, '$$$', 'Y2K Unique Outfit', '31');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Cottagecore', 'Classic Fit', 103.4, '$$', 'Cottagecore Unique Outfit', '22');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Coquette', 'Slim Fit', 414.1, '$$$', 'Soft Pink Outfit', '4');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Cottagecore', 'Slim Fit', 48.28, '$', 'Cottagecore', '13');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Academia', 'Classic Fit', 117.72, '$$', 'Formal Outfit', '17');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Oversized Fit', 190.5, '$$$', 'Miimalistic Formal', '23');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Gorpcore', 'Oversized Fit', 403.65, '$$$', 'Futuristic', '12');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Streetwear', 'Oversized Fit', 804.07, '$$$', 'Simple Streetwear', '33');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Vintage', 'Oversized Fit', 322.28, '$$$', '80s Vintage', '28');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Grunge', 'Oversized Fit', 157.78, '$$', 'Grey-Black Grunge Fit', '20');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Quiet Luxury', 'Slim Fit', 55.28, '$', 'Best Outfit for Work', '15');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Classic Fit', 74.95, '$', 'Easy Style', '1');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Coquette', 'Slim Fit', 86.53, '$', 'Comfy Girl Fit', '2');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Y2K', 'Slim Fit', 62.69, '$', 'Unique 2000s Outfit', '37');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Vintage', 'Classic Fit', 36.48, '$', 'Classic Vintage', '19');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Classic Fit', 141.13, '$$', 'Simple Clean Outfit', '30');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Quiet Luxury', 'Slim Fit', 507.55, '$$$', 'Quiet Luxury Full Outfit', '18');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Streetwear', 'Oversized Fit', 763.87, '$$$', 'Streetwear Unqiue Outfit', '5');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Gorpcore', 'Classic Fit', 79.28, '$', 'Gorpcore Unique Outfit', '3');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Y2K', 'Classic Fit', 74.2, '$', 'Y2K Style', '7');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Vintage', 'Oversized Fit', 304.52, '$$$', 'Retro Outfit', '33');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Slim Fit', 776.4, '$$$', 'Essential', '27');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Quiet Luxury', 'Slim Fit', 576.35, '$$$', 'Simple Luxury', '10');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Gorpcore', 'Oversized Fit', 841.64, '$$$', 'Gorpcore Essential', '16');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Cottagecore', 'Oversized Fit', 194.41, '$$$', 'Cottagecore Essential', '26');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Grunge', 'Slim Fit', 225.42, '$$$', 'Grunge Outfit', '24');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Slim Fit', 567.95, '$$$', 'Winter Simple Outfit', '38');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Academia', 'Classic Fit', 174.42, '$$', 'Elegant Formal', '30');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Grunge', 'Oversized Fit', 108.34, '$$', 'Oversized Grunge Outfit', '36');
INSERT INTO Outfit (Style, BodyFit, Price, CostRating, Name, UserID) VALUES ('Clean', 'Classic Fit', 52.22, '$', 'School Essential', '39');
