insert into Payment_Option (Type, CartID) values ('debit card', '29');
insert into Payment_Option (Type, CartID) values ('debit card', '30');
insert into Payment_Option (Type, CartID) values ('debit card', '11');
insert into Payment_Option (Type, CartID) values ('debit card', '26');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '37');
insert into Payment_Option (Type, CartID) values ('credit card', '15');
insert into Payment_Option (Type, CartID) values ('credit card', '23');
insert into Payment_Option (Type, CartID) values ('debit card', '19');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '8');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '33');
insert into Payment_Option (Type, CartID) values ('debit card', '13');
insert into Payment_Option (Type, CartID) values ('credit card', '6');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '4');
insert into Payment_Option (Type, CartID) values ('credit card', '34');
insert into Payment_Option (Type, CartID) values ('credit card', '10');
insert into Payment_Option (Type, CartID) values ('credit card', '22');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '38');
insert into Payment_Option (Type, CartID) values ('debit card', '24');
insert into Payment_Option (Type, CartID) values ('debit card', '21');
insert into Payment_Option (Type, CartID) values ('credit card', '12');
insert into Payment_Option (Type, CartID) values ('debit card', '2');
insert into Payment_Option (Type, CartID) values ('credit card', '20');
insert into Payment_Option (Type, CartID) values ('credit card', '16');
insert into Payment_Option (Type, CartID) values ('credit card', '27');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '32');
insert into Payment_Option (Type, CartID) values ('debit card', '7');
insert into Payment_Option (Type, CartID) values ('credit card', '28');
insert into Payment_Option (Type, CartID) values ('debit card', '5');
insert into Payment_Option (Type, CartID) values ('debit card', '14');
insert into Payment_Option (Type, CartID) values ('credit card', '1');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '35');
insert into Payment_Option (Type, CartID) values ('credit card', '40');
insert into Payment_Option (Type, CartID) values ('debit card', '36');
insert into Payment_Option (Type, CartID) values ('cash on delivery', '31');
insert into Payment_Option (Type, CartID) values ('credit card', '9');
insert into Payment_Option (Type, CartID) values ('debit card', '25');
insert into Payment_Option (Type, CartID) values ('credit card', '3');
insert into Payment_Option (Type, CartID) values ('credit card', '18');
insert into Payment_Option (Type, CartID) values ('debit card', '17');
insert into Payment_Option (Type, CartID) values ('debit card', '39');
