insert into Persona (Age, Gender, StylePreference, UserID) values (20, 'Female', 'Vintage', '22');
insert into Persona (Age, Gender, StylePreference, UserID) values (42, 'Female', 'Quiet Luxury', '2');
insert into Persona (Age, Gender, StylePreference, UserID) values (16, 'Female', 'Cottagecore', '12');
insert into Persona (Age, Gender, StylePreference, UserID) values (57, 'Female', 'Clean', '33');
insert into Persona (Age, Gender, StylePreference, UserID) values (24, 'Female', 'Grunge', '6');
insert into Persona (Age, Gender, StylePreference, UserID) values (24, 'Male', 'Gorpcore', '13');
insert into Persona (Age, Gender, StylePreference, UserID) values (17, 'Male', 'Academia', '36');
insert into Persona (Age, Gender, StylePreference, UserID) values (54, 'Female', 'Quiet Luxury', '1');
insert into Persona (Age, Gender, StylePreference, UserID) values (32, 'Male', 'Clean', '34');
insert into Persona (Age, Gender, StylePreference, UserID) values (28, 'Female', 'Vintage', '24');
insert into Persona (Age, Gender, StylePreference, UserID) values (25, 'Male', 'Gorpcore', '11');
insert into Persona (Age, Gender, StylePreference, UserID) values (45, 'Male', 'Quiet Luxury', '18');
insert into Persona (Age, Gender, StylePreference, UserID) values (19, 'Female', 'Coquette', '5');
insert into Persona (Age, Gender, StylePreference, UserID) values (29, 'Male', 'Vintage', '26');
insert into Persona (Age, Gender, StylePreference, UserID) values (19, 'Male', 'Grunge', '8');
insert into Persona (Age, Gender, StylePreference, UserID) values (26, 'Male', 'Quiet Luxury', '40');
insert into Persona (Age, Gender, StylePreference, UserID) values (24, 'Male', 'Streetwear', '16');
insert into Persona (Age, Gender, StylePreference, UserID) values (38, 'Female', 'Clean', '37');
insert into Persona (Age, Gender, StylePreference, UserID) values (20, 'Female', 'Coquette', '7');
insert into Persona (Age, Gender, StylePreference, UserID) values (28, 'Male', 'Streetwear', '35');
insert into Persona (Age, Gender, StylePreference, UserID) values (20, 'Female', 'Cottagecore', '14');
insert into Persona (Age, Gender, StylePreference, UserID) values (15, 'Female', 'Academia', '10');
insert into Persona (Age, Gender, StylePreference, UserID) values (29, 'Female', 'Quiet Luxury', '28');
insert into Persona (Age, Gender, StylePreference, UserID) values (37, 'Male', 'Clean', '19');
insert into Persona (Age, Gender, StylePreference, UserID) values (24, 'Male', 'Streetwear', '3');
insert into Persona (Age, Gender, StylePreference, UserID) values (28, 'Male', 'Gorpcore', '32');
insert into Persona (Age, Gender, StylePreference, UserID) values (18, 'Female', 'Y2K', '20');
insert into Persona (Age, Gender, StylePreference, UserID) values (24, 'Female', 'Y2K', '30');
insert into Persona (Age, Gender, StylePreference, UserID) values (18, 'Male', 'Streetwear', '17');
insert into Persona (Age, Gender, StylePreference, UserID) values (25, 'Female', 'Y2K', '39');
insert into Persona (Age, Gender, StylePreference, UserID) values (17, 'Male', 'Gorpcore', '29');
insert into Persona (Age, Gender, StylePreference, UserID) values (42, 'Male', 'Academia', '4');
insert into Persona (Age, Gender, StylePreference, UserID) values (26, 'Female', 'Clean', '23');
insert into Persona (Age, Gender, StylePreference, UserID) values (31, 'Female', 'Quiet Luxury', '38');
insert into Persona (Age, Gender, StylePreference, UserID) values (24, 'Female', 'Y2K', '21');
insert into Persona (Age, Gender, StylePreference, UserID) values (39, 'Female', 'Quiet Luxury', '31');
insert into Persona (Age, Gender, StylePreference, UserID) values (23, 'Male', 'Y2K', '27');
insert into Persona (Age, Gender, StylePreference, UserID) values (35, 'Female', 'Clean', '25');
insert into Persona (Age, Gender, StylePreference, UserID) values (34, 'Male', 'Vintage', '9');
insert into Persona (Age, Gender, StylePreference, UserID) values (47, 'Female', 'Vintage', '15');
