INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-09-17 04:32:03', 90.04, 'Vintage', '8');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-05-06 16:19:14', 162.04, 'Quiet Luxury', '12');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-05-07 00:08:20', 29.97, 'Cottagecore', '19');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-06-27 17:05:39', 81.37, 'Streetwear', '5');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-28 19:29:04', 28.33, 'Clean', '40');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-06-15 20:42:21', 81.06, 'Vintage', '27');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-04-09 19:20:55', 53.31, 'Clean', '3');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-10-06 01:56:50', 58.65, 'Academia', '2');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-09-25 12:46:10', 148.71, 'Quiet Luxury', '20');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-01-14 07:23:36', 57.65, 'Y2K', '4');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-06-17 16:02:38', 45.53, 'Streetwear', '29');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-18 09:52:17', 16.28, 'Academia', '25');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-29 10:09:41', 81.47, 'Quiet Luxury', '11');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-05-04 16:24:52', 65.30, 'Coquette', '1');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-07-11 21:47:42', 92.84, 'Gorpcore', '38');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-10-15 09:39:57', 42.71, 'Gorpcore', '9');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-02-16 23:01:34', 36.25, 'Vintage', '36');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-16 18:28:48', 15.21, 'Coquette', '32');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-15 01:06:26', 81.35, 'Clean', '18');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-08-08 16:32:29', 15.42, 'Cottagecore', '22');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-08-16 19:56:55', 82.38, 'Clean', '23');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-06-30 11:58:17', 52.66, 'Gorpcore', '16');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-14 03:48:45', 52.39, 'Gorpcore', '21');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-22 22:25:12', 71.85, 'Academia', '10');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-09-09 02:30:26', 19.91, 'Y2K', '35');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-04-18 18:47:59', 25.74, 'Clean', '30');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-08-21 03:13:47', 61.33, 'Gorpcore', '26');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-22 00:07:34', 46.13, 'Coquette', '17');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-07-04 21:00:07', 46.13, 'Gorpcore', '28');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-30 18:18:13', 93.55, 'Gorpcore', '14');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-08-14 01:36:02', 52.17, 'Streetwear', '6');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-07-27 13:45:01', 42.42, 'Y2K', '24');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-10-11 18:24:11', 90.64, 'Quiet Luxury', '31');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-03-16 05:30:58', 178.88, 'Quiet Luxury', '37');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-06-14 16:30:26', 93.78, 'Gorpcore', '34');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-08-16 16:45:37', 138.51, 'Clean', '15');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-06-02 09:38:10', 73.43, 'Grunge', '7');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-04-19 02:31:59', 178.89, 'Quiet Luxury', '13');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-01-25 12:11:49', 53.32, 'Grunge', '39');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-12 07:09:22', 87.13, 'Vintage', '33');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-08 22:43:58', 96.31, 'Academia', '9');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2022-12-10 17:29:32', 124.67, 'Quiet Luxury', '16');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-01-13 07:25:27', 51.55, 'Clean', '20');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-07-05 06:54:28', 38.58, 'Coquette', '23');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-02-15 08:43:25', 86.39, 'Vintage', '34');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-27 01:36:09', 14.69, 'Grunge', '37');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-09-22 08:04:37', 71.89, 'Clean', '7');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-02-12 14:50:59', 78.37, 'Quiet Luxury', '8');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-11-04 21:46:37', 96.42, 'Streetwear', '30');
INSERT INTO Purchase_History (PurchaseDate, PurchaseCost, PurchaseAesthetic, UserID) VALUES ('2023-01-06 15:09:00', 17.14, 'Grunge', '24');

/* Insert Purchase History_Outfit */
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('40', '17');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('48', '23');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('23', '25');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('6', '30');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('16', '31');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('49', '44');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('44', '36');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('3', '18');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('9', '41');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('35', '14');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('8', '35');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('2', '45');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('14', '2');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('19', '43');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('4', '38');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('21', '34');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('32', '13');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('10', '26');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('26', '10');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('45', '16');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('13', '6');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('12', '24');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('33', '39');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('30', '9');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('47', '21');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('25', '37');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('38', '12');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('41', '15');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('22', '7');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('34', '4');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('37', '27');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('28', '19');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('7', '42');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('1', '1');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('46', '33');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('11', '46');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('50', '49');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('18', '50');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('15', '40');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('39', '47');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('17', '29');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('27', '22');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('42', '48');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('36', '3');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('31', '32');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('5', '28');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('20', '11');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('29', '20');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('43', '5');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('24', '8');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('48', '22');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('10', '36');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('17', '18');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('25', '2');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('34', '14');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('45', '21');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('39', '44');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('47', '11');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('7', '39');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('13', '29');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('40', '14');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('26', '43');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('14', '5');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('38', '13');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('43', '35');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('27', '33');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('44', '1');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('6', '31');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('12', '12');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('2', '6');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('16', '20');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('18', '47');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('21', '42');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('11', '17');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('8', '16');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('30', '38');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('50', '7');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('32', '24');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('15', '3');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('20', '19');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('3', '37');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('31', '8');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('4', '32');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('36', '23');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('49', '50');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('33', '46');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('1', '40');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('28', '26');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('24', '28');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('23', '35');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('5', '48');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('29', '45');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('22', '30');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('9', '15');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('37', '9');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('19', '27');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('46', '10');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('35', '34');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('42', '41');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('41', '49');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('49', '11');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('48', '2');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('50', '6');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('25', '31');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('24', '30');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('16', '33');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('41', '48');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('6', '34');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('19', '7');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('12', '15');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('43', '38');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('35', '1');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('42', '16');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('34', '44');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('28', '25');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('10', '21');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('40', '50');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('31', '43');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('9', '27');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('37', '3');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('13', '23');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('20', '41');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('27', '10');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('44', '9');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('17', '22');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('15', '8');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('18', '42');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('14', '19');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('3', '27');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('2', '28');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('26', '45');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('29', '26');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('7', '32');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('23', '13');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('38', '5');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('21', '4');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('1', '20');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('8', '36');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('45', '14');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('33', '18');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('5', '39');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('36', '12');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('39', '29');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('4', '47');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('22', '24');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('30', '40');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('32', '49');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('11', '35');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('47', '46');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('46', '17');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('28', '4');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('10', '46');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('37', '18');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('4', '17');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('3', '31');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('2', '23');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('46', '29');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('19', '8');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('8', '22');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('15', '34');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('33', '26');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('26', '9');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('18', '38');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('11', '5');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('36', '6');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('17', '45');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('30', '39');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('50', '11');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('41', '36');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('6', '21');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('48', '47');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('12', '19');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('24', '48');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('21', '20');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('14', '43');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('49', '24');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('16', '27');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('43', '33');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('44', '30');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('40', '49');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('5', '2');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('31', '12');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('35', '50');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('38', '42');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('29', '41');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('13', '13');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('22', '1');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('47', '35');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('23', '3');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('34', '15');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('27', '40');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('42', '37');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('32', '7');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('39', '28');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('25', '44');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('9', '14');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('7', '16');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('1', '32');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('45', '25');
insert into PurchaseHistory_Outfit (PurchaseHistoryID, OutfitID) values ('20', '10');

/* Insert into Wishlist_Item */
insert into Wishlist_Item (WishlistID, ItemID) values ('1', '13');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '49');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '48');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '17');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '59');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '32');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '30');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '46');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '8');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '3');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '40');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '50');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '45');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '38');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '12');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '27');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '34');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '24');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '52');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '23');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '42');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '4');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '6');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '44');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '26');
insert into Wishlist_Item (WishlistID, ItemID) values ('26', '54');
insert into Wishlist_Item (WishlistID, ItemID) values ('27', '7');
insert into Wishlist_Item (WishlistID, ItemID) values ('28', '21');
insert into Wishlist_Item (WishlistID, ItemID) values ('29', '56');
insert into Wishlist_Item (WishlistID, ItemID) values ('30', '19');
insert into Wishlist_Item (WishlistID, ItemID) values ('31', '55');
insert into Wishlist_Item (WishlistID, ItemID) values ('32', '11');
insert into Wishlist_Item (WishlistID, ItemID) values ('33', '31');
insert into Wishlist_Item (WishlistID, ItemID) values ('34', '1');
insert into Wishlist_Item (WishlistID, ItemID) values ('35', '20');
insert into Wishlist_Item (WishlistID, ItemID) values ('36', '15');
insert into Wishlist_Item (WishlistID, ItemID) values ('37', '35');
insert into Wishlist_Item (WishlistID, ItemID) values ('38', '14');
insert into Wishlist_Item (WishlistID, ItemID) values ('39', '47');
insert into Wishlist_Item (WishlistID, ItemID) values ('40', '60');
insert into Wishlist_Item (WishlistID, ItemID) values ('1', '51');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '22');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '28');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '36');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '18');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '25');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '16');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '58');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '5');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '33');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '53');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '2');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '57');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '9');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '10');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '39');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '41');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '29');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '37');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '43');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '35');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '47');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '27');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '49');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '14');
