insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My house', '678 Union Center', 'Portland', 'OR', '97271', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Garreth home', '506 Shoshone Avenue', 'Murfreesboro', 'TN', '37131', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Home', '41860 Sutteridge Court', 'Falls Church', 'VA', '22047', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Office', '6925 Northwestern Drive', 'El Paso', 'TX', '88569', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My apartment', '46 Fieldstone Hill', 'Montpelier', 'VT', '05609', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Win''s home', '0 Forest Park', 'Lancaster', 'PA', '17605', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('College', '71 Talmadge Court', 'San Diego', 'CA', '92121', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Dorm', '215 Karstens Avenue', 'Lincoln', 'NE', '68583', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Teodorski house', '44 Boyd Circle', 'Bakersfield', 'CA', '93311', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My college dorm', '0087 Brown Way', 'Memphis', 'TN', '38150', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My house', '47 Dakota Road', 'Kansas City', 'MO', '64101', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Office', '295 Westerfield Alley', 'Los Angeles', 'CA', '90060', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Apartment', '8 Crownhardt Way', 'Ocala', 'FL', '34479', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Dorm', '61176 Knutson Trail', 'Great Neck', 'NY', '11024', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Mailroom', '90 Bultman Lane', 'Saint Paul', 'MN', '55115', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My apartment', '1 Tennyson Crossing', 'Des Moines', 'IA', '50335', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Rica''s apartment', '689 Arkansas Center', 'Scranton', 'PA', '18505', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Peter''s room', '4 Hanover Pass', 'Fort Worth', 'TX', '76110', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My house', '88 Talmadge Park', 'Billings', 'MT', '59105', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Parent''s house', '95027 Little Fleur Drive', 'Buffalo', 'NY', '14225', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Home', '4 Waywood Crossing', 'Salt Lake City', 'UT', '84130', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Office building', '6 Hauk Trail', 'Irvine', 'CA', '92710', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('College dorm', '21 Rusk Trail', 'San Jose', 'CA', '95173', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Andrew''s apartment', '36537 Monument Alley', 'Richmond', 'VA', '23213', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Second house', '85180 Schurz Street', 'Saint Louis', 'MO', '63150', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Patel''s house', '02341 Jay Avenue', 'Dayton', 'OH', '45454', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Rea''s apartment', '77 Dapin Trail', 'Irving', 'TX', '75037', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Apartment building', '9 Kensington Crossing', 'Norfolk', 'VA', '23514', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Home', '57123 Mendota Point', 'Boston', 'MA', '02124', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Parent''s house', '78986 Talmadge Lane', 'Kansas City', 'MO', '64114', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Family''s house', '1 Carey Junction', 'Wichita', 'KS', '67230', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Home', '3094 Kropf Place', 'Memphis', 'TN', '38188', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Apartment', '4895 Miller Park', 'Greeley', 'CO', '80638', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Building mailroom', '932 Northwestern Court', 'Simi Valley', 'CA', '93094', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Rea''s home', '8547 Anzinger Drive', 'Denver', 'CO', '80255', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Dorm', '70 Grim Plaza', 'Tampa', 'FL', '33647', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Mailroom', '74 Anderson Drive', 'Richmond', 'VA', '23213', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('College', '09039 Kinsman Trail', 'Montgomery', 'AL', '36104', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Second apartment', '5717 Aberg Park', 'Nashville', 'TN', '37235', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Justo''s house', '722 Onsgard Alley', 'Florence', 'SC', '29505', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Hebert''s', '8 Prairieview Center', 'Springfield', 'MO', '65898', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('My house', '0 Gale Pass', 'Baltimore', 'MD', '21211', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Apartment 2', '2 Forest Run Junction', 'Pasadena', 'CA', '91109', '5');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Jakie House', '9 Springs Circle', 'Philadelphia', 'PA', '19093', '3');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Apartment Mail', '5579 Park Meadow Court', 'Albany', 'NY', '12237', '2');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Office Building', '4 Buhler Crossing', 'Tampa', 'FL', '33615', '6');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Izak''s House', '052 Bonner Plaza', 'Homestead', 'FL', '33034', '1');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Mom''s House', '34261 Homewood Plaza', 'Columbus', 'OH', '43204', '7');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Uni Dorm', '0 Summit Alley', 'Milwaukee', 'WI', '53205', '4');
insert into Shipping_Info (Name, Street, City, State, ZipCode, ShippingOptionID) values ('Uni', '127 Burrows Circle', 'El Paso', 'TX', '79916', '4');
