insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 99.12, 1, 1);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 182.55, 3, 2);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 67.80, 7, 3);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 55.99, 2, 4);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 35.99, 6, 5);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 74.50, 6, 6);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 59.30, 4, 7);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 157.75, 3, 8);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 24.95, 7, 9);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 28.18, 6, 10);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 96.88, 1, 11);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 68.01, 5, 12);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 48.50, 7, 13);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 57.04, 5, 14);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 55.64, 3, 15);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 28.08, 2, 16);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 120.55, 4, 17);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 18.65, 3, 18);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 51.75, 1, 19);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 123.05, 2, 20);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 33.50, 2, 21);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 13.35, 4, 22);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 75.99, 6, 23);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 18.23, 3, 24);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 09.25, 1, 25);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 71.69, 5, 26);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 42.69, 2, 27);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 100.50, 7, 28);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 66.90, 4, 29);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 26.00, 3, 30);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 51.55, 2, 31);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 16.90, 2, 32);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 213.35, 4, 33);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 45.95, 1, 34);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 35.99, 1, 35);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 40.92, 2, 36);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 17.63, 1, 37);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 39.00, 2, 38);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 19.13, 3, 39);
insert into Shopping_Cart (Cost, ShippingOptionID, UserID) values ( 97.50, 3, 40);

insert into ShoppingCart_Item (CartID, ItemID) values ('1', '13');
insert into ShoppingCart_Item (CartID, ItemID) values ('2', '21');
insert into ShoppingCart_Item (CartID, ItemID) values ('3', '16');
insert into ShoppingCart_Item (CartID, ItemID) values ('4', '46');
insert into ShoppingCart_Item (CartID, ItemID) values ('5', '26');
insert into ShoppingCart_Item (CartID, ItemID) values ('6', '7');
insert into ShoppingCart_Item (CartID, ItemID) values ('7', '60');
insert into ShoppingCart_Item (CartID, ItemID) values ('8', '57');
insert into ShoppingCart_Item (CartID, ItemID) values ('9', '42');
insert into ShoppingCart_Item (CartID, ItemID) values ('10', '54');
insert into ShoppingCart_Item (CartID, ItemID) values ('11', '25');
insert into ShoppingCart_Item (CartID, ItemID) values ('12', '29');
insert into ShoppingCart_Item (CartID, ItemID) values ('13', '1');
insert into ShoppingCart_Item (CartID, ItemID) values ('14', '41');
insert into ShoppingCart_Item (CartID, ItemID) values ('15', '52');
insert into ShoppingCart_Item (CartID, ItemID) values ('16', '55');
insert into ShoppingCart_Item (CartID, ItemID) values ('17', '45');
insert into ShoppingCart_Item (CartID, ItemID) values ('18', '10');
insert into ShoppingCart_Item (CartID, ItemID) values ('19', '59');
insert into ShoppingCart_Item (CartID, ItemID) values ('20', '3');
insert into ShoppingCart_Item (CartID, ItemID) values ('21', '36');
insert into ShoppingCart_Item (CartID, ItemID) values ('22', '5');
insert into ShoppingCart_Item (CartID, ItemID) values ('23', '35');
insert into ShoppingCart_Item (CartID, ItemID) values ('24', '4');
insert into ShoppingCart_Item (CartID, ItemID) values ('25', '22');
insert into ShoppingCart_Item (CartID, ItemID) values ('26', '32');
insert into ShoppingCart_Item (CartID, ItemID) values ('27', '9');
insert into ShoppingCart_Item (CartID, ItemID) values ('28', '47');
insert into ShoppingCart_Item (CartID, ItemID) values ('29', '50');
insert into ShoppingCart_Item (CartID, ItemID) values ('30', '28');
insert into ShoppingCart_Item (CartID, ItemID) values ('31', '34');
insert into ShoppingCart_Item (CartID, ItemID) values ('32', '20');
insert into ShoppingCart_Item (CartID, ItemID) values ('33', '18');
insert into ShoppingCart_Item (CartID, ItemID) values ('34', '11');
insert into ShoppingCart_Item (CartID, ItemID) values ('35', '39');
insert into ShoppingCart_Item (CartID, ItemID) values ('36', '12');
insert into ShoppingCart_Item (CartID, ItemID) values ('37', '14');
insert into ShoppingCart_Item (CartID, ItemID) values ('38', '40');
insert into ShoppingCart_Item (CartID, ItemID) values ('39', '38');
insert into ShoppingCart_Item (CartID, ItemID) values ('40', '31');
insert into ShoppingCart_Item (CartID, ItemID) values ('1', '51');
insert into ShoppingCart_Item (CartID, ItemID) values ('2', '30');
insert into ShoppingCart_Item (CartID, ItemID) values ('3', '24');
insert into ShoppingCart_Item (CartID, ItemID) values ('4', '53');
insert into ShoppingCart_Item (CartID, ItemID) values ('5', '33');
insert into ShoppingCart_Item (CartID, ItemID) values ('6', '15');
insert into ShoppingCart_Item (CartID, ItemID) values ('7', '8');
insert into ShoppingCart_Item (CartID, ItemID) values ('8', '19');
insert into ShoppingCart_Item (CartID, ItemID) values ('9', '6');
insert into ShoppingCart_Item (CartID, ItemID) values ('10', '44');
insert into ShoppingCart_Item (CartID, ItemID) values ('11', '58');
insert into ShoppingCart_Item (CartID, ItemID) values ('12', '49');
insert into ShoppingCart_Item (CartID, ItemID) values ('13', '48');
insert into ShoppingCart_Item (CartID, ItemID) values ('14', '17');
insert into ShoppingCart_Item (CartID, ItemID) values ('15', '27');
insert into ShoppingCart_Item (CartID, ItemID) values ('16', '37');
insert into ShoppingCart_Item (CartID, ItemID) values ('17', '23');
insert into ShoppingCart_Item (CartID, ItemID) values ('18', '2');
insert into ShoppingCart_Item (CartID, ItemID) values ('19', '43');
insert into ShoppingCart_Item (CartID, ItemID) values ('20', '56');
insert into ShoppingCart_Item (CartID, ItemID) values ('21', '38');
insert into ShoppingCart_Item (CartID, ItemID) values ('22', '51');
insert into ShoppingCart_Item (CartID, ItemID) values ('23', '26');
insert into ShoppingCart_Item (CartID, ItemID) values ('24', '43');
insert into ShoppingCart_Item (CartID, ItemID) values ('25', '12');
insert into ShoppingCart_Item (CartID, ItemID) values ('26', '35');
insert into ShoppingCart_Item (CartID, ItemID) values ('27', '28');
insert into ShoppingCart_Item (CartID, ItemID) values ('28', '39');
insert into ShoppingCart_Item (CartID, ItemID) values ('29', '37');
insert into ShoppingCart_Item (CartID, ItemID) values ('30', '52');
insert into ShoppingCart_Item (CartID, ItemID) values ('31', '46');
insert into ShoppingCart_Item (CartID, ItemID) values ('32', '45');
insert into ShoppingCart_Item (CartID, ItemID) values ('33', '25');
insert into ShoppingCart_Item (CartID, ItemID) values ('34', '30');
insert into ShoppingCart_Item (CartID, ItemID) values ('35', '33');
insert into ShoppingCart_Item (CartID, ItemID) values ('36', '6');
insert into ShoppingCart_Item (CartID, ItemID) values ('37', '44');
insert into ShoppingCart_Item (CartID, ItemID) values ('38', '41');
insert into ShoppingCart_Item (CartID, ItemID) values ('39', '29');
insert into ShoppingCart_Item (CartID, ItemID) values ('40', '41');
insert into ShoppingCart_Item (CartID, ItemID) values ('1', '31');
insert into ShoppingCart_Item (CartID, ItemID) values ('2', '50');
insert into ShoppingCart_Item (CartID, ItemID) values ('3', '42');
insert into ShoppingCart_Item (CartID, ItemID) values ('4', '4');
insert into ShoppingCart_Item (CartID, ItemID) values ('5', '54');
insert into ShoppingCart_Item (CartID, ItemID) values ('6', '5');
insert into ShoppingCart_Item (CartID, ItemID) values ('7', '15');
insert into ShoppingCart_Item (CartID, ItemID) values ('8', '58');
insert into ShoppingCart_Item (CartID, ItemID) values ('9', '23');
insert into ShoppingCart_Item (CartID, ItemID) values ('10', '55');
insert into ShoppingCart_Item (CartID, ItemID) values ('11', '8');
insert into ShoppingCart_Item (CartID, ItemID) values ('12', '16');
insert into ShoppingCart_Item (CartID, ItemID) values ('13', '56');
insert into ShoppingCart_Item (CartID, ItemID) values ('14', '1');
insert into ShoppingCart_Item (CartID, ItemID) values ('15', '9');
insert into ShoppingCart_Item (CartID, ItemID) values ('16', '47');
insert into ShoppingCart_Item (CartID, ItemID) values ('17', '17');
insert into ShoppingCart_Item (CartID, ItemID) values ('18', '60');
insert into ShoppingCart_Item (CartID, ItemID) values ('19', '14');
insert into ShoppingCart_Item (CartID, ItemID) values ('20', '48');
insert into ShoppingCart_Item (CartID, ItemID) values ('21', '22');
insert into ShoppingCart_Item (CartID, ItemID) values ('22', '19');
insert into ShoppingCart_Item (CartID, ItemID) values ('23', '2');
insert into ShoppingCart_Item (CartID, ItemID) values ('24', '13');
insert into ShoppingCart_Item (CartID, ItemID) values ('25', '59');
insert into ShoppingCart_Item (CartID, ItemID) values ('26', '3');
insert into ShoppingCart_Item (CartID, ItemID) values ('27', '34');
insert into ShoppingCart_Item (CartID, ItemID) values ('28', '49');
insert into ShoppingCart_Item (CartID, ItemID) values ('29', '18');
insert into ShoppingCart_Item (CartID, ItemID) values ('30', '57');
insert into ShoppingCart_Item (CartID, ItemID) values ('31', '53');
insert into ShoppingCart_Item (CartID, ItemID) values ('32', '36');
insert into ShoppingCart_Item (CartID, ItemID) values ('33', '27');
insert into ShoppingCart_Item (CartID, ItemID) values ('34', '24');
insert into ShoppingCart_Item (CartID, ItemID) values ('35', '21');
insert into ShoppingCart_Item (CartID, ItemID) values ('36', '20');
insert into ShoppingCart_Item (CartID, ItemID) values ('37', '7');
insert into ShoppingCart_Item (CartID, ItemID) values ('38', '10');
insert into ShoppingCart_Item (CartID, ItemID) values ('39', '11');
insert into ShoppingCart_Item (CartID, ItemID) values ('40', '32');
insert into ShoppingCart_Item (CartID, ItemID) values ('1', '57');
insert into ShoppingCart_Item (CartID, ItemID) values ('2', '18');
insert into ShoppingCart_Item (CartID, ItemID) values ('3', '45');
insert into ShoppingCart_Item (CartID, ItemID) values ('4', '35');
insert into ShoppingCart_Item (CartID, ItemID) values ('5', '8');
insert into ShoppingCart_Item (CartID, ItemID) values ('6', '4');
insert into ShoppingCart_Item (CartID, ItemID) values ('7', '21');
insert into ShoppingCart_Item (CartID, ItemID) values ('8', '43');
insert into ShoppingCart_Item (CartID, ItemID) values ('9', '36');
insert into ShoppingCart_Item (CartID, ItemID) values ('10', '39');
insert into ShoppingCart_Item (CartID, ItemID) values ('11', '7');
insert into ShoppingCart_Item (CartID, ItemID) values ('12', '59');
insert into ShoppingCart_Item (CartID, ItemID) values ('13', '23');
insert into ShoppingCart_Item (CartID, ItemID) values ('14', '53');
insert into ShoppingCart_Item (CartID, ItemID) values ('15', '12');
insert into ShoppingCart_Item (CartID, ItemID) values ('16', '30');
insert into ShoppingCart_Item (CartID, ItemID) values ('17', '25');
insert into ShoppingCart_Item (CartID, ItemID) values ('18', '37');
insert into ShoppingCart_Item (CartID, ItemID) values ('19', '3');
insert into ShoppingCart_Item (CartID, ItemID) values ('20', '6');
insert into ShoppingCart_Item (CartID, ItemID) values ('21', '2');
insert into ShoppingCart_Item (CartID, ItemID) values ('22', '54');
insert into ShoppingCart_Item (CartID, ItemID) values ('23', '10');
insert into ShoppingCart_Item (CartID, ItemID) values ('24', '15');
insert into ShoppingCart_Item (CartID, ItemID) values ('25', '28');
insert into ShoppingCart_Item (CartID, ItemID) values ('26', '46');
insert into ShoppingCart_Item (CartID, ItemID) values ('27', '51');
insert into ShoppingCart_Item (CartID, ItemID) values ('28', '17');
insert into ShoppingCart_Item (CartID, ItemID) values ('29', '55');
insert into ShoppingCart_Item (CartID, ItemID) values ('30', '42');
insert into ShoppingCart_Item (CartID, ItemID) values ('31', '11');
insert into ShoppingCart_Item (CartID, ItemID) values ('32', '49');
insert into ShoppingCart_Item (CartID, ItemID) values ('33', '33');
insert into ShoppingCart_Item (CartID, ItemID) values ('34', '47');
insert into ShoppingCart_Item (CartID, ItemID) values ('35', '56');
insert into ShoppingCart_Item (CartID, ItemID) values ('36', '16');
insert into ShoppingCart_Item (CartID, ItemID) values ('37', '1');
insert into ShoppingCart_Item (CartID, ItemID) values ('38', '50');
insert into ShoppingCart_Item (CartID, ItemID) values ('39', '58');
insert into ShoppingCart_Item (CartID, ItemID) values ('40', '26');
insert into ShoppingCart_Item (CartID, ItemID) values ('1', '30');
insert into ShoppingCart_Item (CartID, ItemID) values ('2', '22');
insert into ShoppingCart_Item (CartID, ItemID) values ('3', '20');
insert into ShoppingCart_Item (CartID, ItemID) values ('4', '40');
insert into ShoppingCart_Item (CartID, ItemID) values ('5', '38');
insert into ShoppingCart_Item (CartID, ItemID) values ('6', '32');
insert into ShoppingCart_Item (CartID, ItemID) values ('7', '6');
insert into ShoppingCart_Item (CartID, ItemID) values ('8', '29');
insert into ShoppingCart_Item (CartID, ItemID) values ('9', '14');
insert into ShoppingCart_Item (CartID, ItemID) values ('10', '5');
insert into ShoppingCart_Item (CartID, ItemID) values ('11', '52');
insert into ShoppingCart_Item (CartID, ItemID) values ('12', '27');
insert into ShoppingCart_Item (CartID, ItemID) values ('13', '19');
insert into ShoppingCart_Item (CartID, ItemID) values ('14', '48');
insert into ShoppingCart_Item (CartID, ItemID) values ('15', '19');
insert into ShoppingCart_Item (CartID, ItemID) values ('16', '24');
insert into ShoppingCart_Item (CartID, ItemID) values ('17', '44');
insert into ShoppingCart_Item (CartID, ItemID) values ('18', '34');
insert into ShoppingCart_Item (CartID, ItemID) values ('19', '13');
insert into ShoppingCart_Item (CartID, ItemID) values ('20', '41');
insert into ShoppingCart_Item (CartID, ItemID) values ('21', '55');
insert into ShoppingCart_Item (CartID, ItemID) values ('22', '48');
insert into ShoppingCart_Item (CartID, ItemID) values ('23', '34');
insert into ShoppingCart_Item (CartID, ItemID) values ('24', '36');
insert into ShoppingCart_Item (CartID, ItemID) values ('25', '1');
insert into ShoppingCart_Item (CartID, ItemID) values ('26', '13');
insert into ShoppingCart_Item (CartID, ItemID) values ('27', '26');
insert into ShoppingCart_Item (CartID, ItemID) values ('28', '18');
insert into ShoppingCart_Item (CartID, ItemID) values ('29', '7');
insert into ShoppingCart_Item (CartID, ItemID) values ('30', '39');
insert into ShoppingCart_Item (CartID, ItemID) values ('31', '16');
insert into ShoppingCart_Item (CartID, ItemID) values ('32', '19');
insert into ShoppingCart_Item (CartID, ItemID) values ('33', '52');
insert into ShoppingCart_Item (CartID, ItemID) values ('34', '60');
insert into ShoppingCart_Item (CartID, ItemID) values ('35', '44');
insert into ShoppingCart_Item (CartID, ItemID) values ('36', '56');
insert into ShoppingCart_Item (CartID, ItemID) values ('37', '11');
insert into ShoppingCart_Item (CartID, ItemID) values ('38', '21');
insert into ShoppingCart_Item (CartID, ItemID) values ('39', '37');
insert into ShoppingCart_Item (CartID, ItemID) values ('40', '45');
