insert into Style (Color, AestheticName, TrendRating) values ('Teal', 'Vintage', 7);
insert into Style (Color, AestheticName, TrendRating) values ('Blue', 'Gorpcore', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Black', 'Quiet Luxury', 9);
insert into Style (Color, AestheticName, TrendRating) values ('Pink', 'Cottagecore', 4);
insert into Style (Color, AestheticName, TrendRating) values ('Red', 'Vintage', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Beige', 'Vintage', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Brown', 'Grunge', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Crimson', 'Academia', 4);
insert into Style (Color, AestheticName, TrendRating) values ('Sage', 'Cottagecore', 4);
insert into Style (Color, AestheticName, TrendRating) values ('Violet', 'Coquette', 7);
insert into Style (Color, AestheticName, TrendRating) values ('Blue', 'Y2K', 4);
insert into Style (Color, AestheticName, TrendRating) values ('Black', 'Streetwear', 5);
insert into Style (Color, AestheticName, TrendRating) values ('Khaki', 'Quiet Luxury', 9);
insert into Style (Color, AestheticName, TrendRating) values ('Yellow', 'Vintage', 7);
insert into Style (Color, AestheticName, TrendRating) values ('Grey', 'Clean', 7);
insert into Style (Color, AestheticName, TrendRating) values ('Blue', 'Streetwear', 5);
insert into Style (Color, AestheticName, TrendRating) values ('Black', 'Grunge', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Goldenrod', 'Quiet Luxury', 9);
insert into Style (Color, AestheticName, TrendRating) values ('Moss', 'Grunge', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Lime', 'Y2K', 4);
insert into Style (Color, AestheticName, TrendRating) values ('Maroon', 'Quiet Luxury', 9);
insert into Style (Color, AestheticName, TrendRating) values ('Beige', 'Clean', 8);
insert into Style (Color, AestheticName, TrendRating) values ('Black', 'Gorpcore', 6);
insert into Style (Color, AestheticName, TrendRating) values ('Grey', 'Gorpcore', 6);
insert into Style (Color, AestheticName, TrendRating) values ('White', 'Quiet Luxury', 9);
insert into Style (Color, AestheticName, TrendRating) values ('White', 'Academia', 4);
insert into Style (Color, AestheticName, TrendRating) values ('Brown', 'Clean', 8);
insert into Style (Color, AestheticName, TrendRating) values ('White', 'Streetwear', 5);
insert into Style (Color, AestheticName, TrendRating) values ('Blush', 'Coquette', 7);
insert into Style (Color, AestheticName, TrendRating) values ('Red', 'Clean', 8);
