insert into Wishlist (Name, UserID) values ('Amanda''s Wishlist', '1');
insert into Wishlist (Name, UserID) values ('Wishlist', '2');
insert into Wishlist (Name, UserID) values ('Celine''s Fav', '3');
insert into Wishlist (Name, UserID) values ('My Favorites', '4');
insert into Wishlist (Name, UserID) values ('My wishlist', '5');
insert into Wishlist (Name, UserID) values ('Wants', '6');
insert into Wishlist (Name, UserID) values ('To buy', '7');
insert into Wishlist (Name, UserID) values ('Favs', '8');
insert into Wishlist (Name, UserID) values ('My favs', '9');
insert into Wishlist (Name, UserID) values ('Christmas Wishlist', '10');
insert into Wishlist (Name, UserID) values ('Dan''s Fav', '11');
insert into Wishlist (Name, UserID) values ('Wish', '12');
insert into Wishlist (Name, UserID) values ('My wishlist', '13');
insert into Wishlist (Name, UserID) values ('Favorites', '14');
insert into Wishlist (Name, UserID) values ('Outfits I want', '15');
insert into Wishlist (Name, UserID) values ('Doris Wishlist', '16');
insert into Wishlist (Name, UserID) values ('Wishlist', '17');
insert into Wishlist (Name, UserID) values ('Newyear wishlist', '18');
insert into Wishlist (Name, UserID) values ('Buy for Christmas', '19');
insert into Wishlist (Name, UserID) values ('Outfit planner', '20');
insert into Wishlist (Name, UserID) values ('My favorite', '21');
insert into Wishlist (Name, UserID) values ('Holiday Wishlist', '22');
insert into Wishlist (Name, UserID) values ('Favorites', '23');
insert into Wishlist (Name, UserID) values ('Gar''s Wishlist', '24');
insert into Wishlist (Name, UserID) values ('Things I want', '25');
insert into Wishlist (Name, UserID) values ('Christmas present', '26');
insert into Wishlist (Name, UserID) values ('Newyear wants', '27');
insert into Wishlist (Name, UserID) values ('My favorite outfits', '28');
insert into Wishlist (Name, UserID) values ('My favorite items', '29');
insert into Wishlist (Name, UserID) values ('Wishlist', '30');
insert into Wishlist (Name, UserID) values ('Chance''s Wishlist', '31');
insert into Wishlist (Name, UserID) values ('Outfits I want', '32');
insert into Wishlist (Name, UserID) values ('Holiday gifts', '33');
insert into Wishlist (Name, UserID) values ('Favs', '34');
insert into Wishlist (Name, UserID) values ('My Wishlist', '35');
insert into Wishlist (Name, UserID) values ('To buy', '36');
insert into Wishlist (Name, UserID) values ('Outfits for work', '37');
insert into Wishlist (Name, UserID) values ('Outfits for holiday', '38');
insert into Wishlist (Name, UserID) values ('Wishlist', '39');
insert into Wishlist (Name, UserID) values ('Favorites', '40');


insert into Wishlist_Item (WishlistID, ItemID) values ('1', '13');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '49');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '48');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '17');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '59');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '32');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '30');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '46');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '8');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '3');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '40');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '50');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '45');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '38');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '12');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '27');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '34');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '24');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '52');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '23');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '42');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '4');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '6');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '44');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '26');
insert into Wishlist_Item (WishlistID, ItemID) values ('26', '54');
insert into Wishlist_Item (WishlistID, ItemID) values ('27', '7');
insert into Wishlist_Item (WishlistID, ItemID) values ('28', '21');
insert into Wishlist_Item (WishlistID, ItemID) values ('29', '56');
insert into Wishlist_Item (WishlistID, ItemID) values ('30', '19');
insert into Wishlist_Item (WishlistID, ItemID) values ('31', '55');
insert into Wishlist_Item (WishlistID, ItemID) values ('32', '11');
insert into Wishlist_Item (WishlistID, ItemID) values ('33', '31');
insert into Wishlist_Item (WishlistID, ItemID) values ('34', '1');
insert into Wishlist_Item (WishlistID, ItemID) values ('35', '20');
insert into Wishlist_Item (WishlistID, ItemID) values ('36', '15');
insert into Wishlist_Item (WishlistID, ItemID) values ('37', '35');
insert into Wishlist_Item (WishlistID, ItemID) values ('38', '14');
insert into Wishlist_Item (WishlistID, ItemID) values ('39', '47');
insert into Wishlist_Item (WishlistID, ItemID) values ('40', '60');
insert into Wishlist_Item (WishlistID, ItemID) values ('1', '51');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '22');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '28');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '36');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '18');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '25');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '16');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '58');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '5');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '33');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '53');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '2');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '57');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '9');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '10');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '39');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '41');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '29');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '37');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '43');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '35');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '47');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '27');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '49');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '14');
insert into Wishlist_Item (WishlistID, ItemID) values ('26', '2');
insert into Wishlist_Item (WishlistID, ItemID) values ('27', '3');
insert into Wishlist_Item (WishlistID, ItemID) values ('28', '60');
insert into Wishlist_Item (WishlistID, ItemID) values ('29', '19');
insert into Wishlist_Item (WishlistID, ItemID) values ('30', '39');
insert into Wishlist_Item (WishlistID, ItemID) values ('31', '26');
insert into Wishlist_Item (WishlistID, ItemID) values ('32', '4');
insert into Wishlist_Item (WishlistID, ItemID) values ('33', '25');
insert into Wishlist_Item (WishlistID, ItemID) values ('34', '50');
insert into Wishlist_Item (WishlistID, ItemID) values ('35', '54');
insert into Wishlist_Item (WishlistID, ItemID) values ('36', '31');
insert into Wishlist_Item (WishlistID, ItemID) values ('37', '8');
insert into Wishlist_Item (WishlistID, ItemID) values ('38', '21');
insert into Wishlist_Item (WishlistID, ItemID) values ('39', '6');
insert into Wishlist_Item (WishlistID, ItemID) values ('40', '57');
insert into Wishlist_Item (WishlistID, ItemID) values ('1', '7');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '12');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '1');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '29');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '28');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '40');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '48');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '23');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '38');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '11');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '58');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '5');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '15');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '44');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '9');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '36');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '45');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '52');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '41');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '55');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '18');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '33');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '37');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '46');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '51');
insert into Wishlist_Item (WishlistID, ItemID) values ('26', '53');
insert into Wishlist_Item (WishlistID, ItemID) values ('27', '59');
insert into Wishlist_Item (WishlistID, ItemID) values ('28', '56');
insert into Wishlist_Item (WishlistID, ItemID) values ('29', '30');
insert into Wishlist_Item (WishlistID, ItemID) values ('30', '22');
insert into Wishlist_Item (WishlistID, ItemID) values ('31', '17');
insert into Wishlist_Item (WishlistID, ItemID) values ('32', '20');
insert into Wishlist_Item (WishlistID, ItemID) values ('33', '16');
insert into Wishlist_Item (WishlistID, ItemID) values ('34', '42');
insert into Wishlist_Item (WishlistID, ItemID) values ('35', '43');
insert into Wishlist_Item (WishlistID, ItemID) values ('36', '34');
insert into Wishlist_Item (WishlistID, ItemID) values ('37', '10');
insert into Wishlist_Item (WishlistID, ItemID) values ('38', '32');
insert into Wishlist_Item (WishlistID, ItemID) values ('39', '13');
insert into Wishlist_Item (WishlistID, ItemID) values ('40', '24');
insert into Wishlist_Item (WishlistID, ItemID) values ('1', '20');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '1');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '18');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '22');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '37');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '48');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '10');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '32');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '40');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '34');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '43');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '11');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '55');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '26');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '3');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '7');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '13');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '31');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '36');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '16');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '28');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '19');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '21');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '47');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '6');
insert into Wishlist_Item (WishlistID, ItemID) values ('26', '4');
insert into Wishlist_Item (WishlistID, ItemID) values ('27', '49');
insert into Wishlist_Item (WishlistID, ItemID) values ('28', '39');
insert into Wishlist_Item (WishlistID, ItemID) values ('29', '33');
insert into Wishlist_Item (WishlistID, ItemID) values ('30', '14');
insert into Wishlist_Item (WishlistID, ItemID) values ('31', '51');
insert into Wishlist_Item (WishlistID, ItemID) values ('32', '50');
insert into Wishlist_Item (WishlistID, ItemID) values ('33', '54');
insert into Wishlist_Item (WishlistID, ItemID) values ('34', '17');
insert into Wishlist_Item (WishlistID, ItemID) values ('35', '27');
insert into Wishlist_Item (WishlistID, ItemID) values ('36', '30');
insert into Wishlist_Item (WishlistID, ItemID) values ('37', '44');
insert into Wishlist_Item (WishlistID, ItemID) values ('38', '2');
insert into Wishlist_Item (WishlistID, ItemID) values ('39', '12');
insert into Wishlist_Item (WishlistID, ItemID) values ('40', '29');
insert into Wishlist_Item (WishlistID, ItemID) values ('1', '35');
insert into Wishlist_Item (WishlistID, ItemID) values ('2', '8');
insert into Wishlist_Item (WishlistID, ItemID) values ('3', '42');
insert into Wishlist_Item (WishlistID, ItemID) values ('4', '56');
insert into Wishlist_Item (WishlistID, ItemID) values ('5', '41');
insert into Wishlist_Item (WishlistID, ItemID) values ('6', '23');
insert into Wishlist_Item (WishlistID, ItemID) values ('7', '9');
insert into Wishlist_Item (WishlistID, ItemID) values ('8', '60');
insert into Wishlist_Item (WishlistID, ItemID) values ('9', '53');
insert into Wishlist_Item (WishlistID, ItemID) values ('10', '45');
insert into Wishlist_Item (WishlistID, ItemID) values ('11', '15');
insert into Wishlist_Item (WishlistID, ItemID) values ('12', '15');
insert into Wishlist_Item (WishlistID, ItemID) values ('13', '24');
insert into Wishlist_Item (WishlistID, ItemID) values ('14', '55');
insert into Wishlist_Item (WishlistID, ItemID) values ('15', '59');
insert into Wishlist_Item (WishlistID, ItemID) values ('16', '52');
insert into Wishlist_Item (WishlistID, ItemID) values ('17', '58');
insert into Wishlist_Item (WishlistID, ItemID) values ('18', '25');
insert into Wishlist_Item (WishlistID, ItemID) values ('19', '38');
insert into Wishlist_Item (WishlistID, ItemID) values ('20', '46');
insert into Wishlist_Item (WishlistID, ItemID) values ('21', '22');
insert into Wishlist_Item (WishlistID, ItemID) values ('22', '42');
insert into Wishlist_Item (WishlistID, ItemID) values ('23', '55');
insert into Wishlist_Item (WishlistID, ItemID) values ('24', '48');
insert into Wishlist_Item (WishlistID, ItemID) values ('25', '24');
insert into Wishlist_Item (WishlistID, ItemID) values ('26', '52');
insert into Wishlist_Item (WishlistID, ItemID) values ('27', '12');
insert into Wishlist_Item (WishlistID, ItemID) values ('28', '50');
insert into Wishlist_Item (WishlistID, ItemID) values ('29', '8');
insert into Wishlist_Item (WishlistID, ItemID) values ('30', '21');
insert into Wishlist_Item (WishlistID, ItemID) values ('31', '60');
insert into Wishlist_Item (WishlistID, ItemID) values ('32', '47');
insert into Wishlist_Item (WishlistID, ItemID) values ('33', '4');
insert into Wishlist_Item (WishlistID, ItemID) values ('34', '13');
insert into Wishlist_Item (WishlistID, ItemID) values ('35', '29');
insert into Wishlist_Item (WishlistID, ItemID) values ('36', '10');
insert into Wishlist_Item (WishlistID, ItemID) values ('37', '33');
insert into Wishlist_Item (WishlistID, ItemID) values ('38', '37');
insert into Wishlist_Item (WishlistID, ItemID) values ('39', '14');
insert into Wishlist_Item (WishlistID, ItemID) values ('40', '43');
